#
# MAKEFILE for vfru library
#

CFLAGS = /D_WINDOWS /DWINDOWS /W3 /GR \
 /O1 /DNDEBUG /FD /EHsc /MD \
 /I../sg /I../util

OBJS = vfruStl.obj vfruWfObj.obj
TARGET = vfru.lib

CXX = cl -nologo -c
AR = lib /NOLOGO
LINK = link

.SUFFIXES: .cpp .obj

.cpp.obj:
	$(CXX) $(CFLAGS) $<


vfru.lib : $(OBJS)
	$(AR) -out:$@ $** 


clean : 
	-@erase *.obj

distclean : clean
	-@erase $(TARGET) vc*.*
