#

G = -O2

include ../sg/make.linux

VFRLIBDIR=../sg

INC = -I. -I../sg -I../util
CFLAGS = $(INC) $(G) $(PICFLAG) $(CFOPT)
CXXFLAGS = $(CFLAGS)
LDLIBS = 
LDFLAGS = $(CFLAGS)

OBJS = vfruStl.o vfruWfObj.o

XOPTNAME = u
LIB_DYNAMIC = libvfr$(XOPTNAME)$(STYLE).so
LIB_STATIC = libvfr$(XOPTNAME)$(STYLE).a


all : lib

lib : $(LIB_DYNAMIC) $(LIB_STATIC)

$(LIB_DYNAMIC) : $(OBJS)
	$(CXX) $(LDFOPT) $(LDFLAGS) -o $@ $(OBJS) -L../sg $(VFR_DLIB) $(LDLIBS)

$(LIB_STATIC) : $(OBJS)
	ar -curv $@ $(OBJS)
	$(RANLIB) $@

clean :
	$(RM) *.o *~ a.out core

depend:
	$(DEPEND) vfr$(XOPTNAME)*.[hC]

install: $(LIB_STATIC)
	install -d ../dist/lib
	install $(LIB_STATIC) ../dist/lib

# DO NOT DELETE

