#
# MAKEFILE for vfru library
#

CFLAGS = /W3 /wo4244 /EHsc /D_WINDOWS /DWINDOWS /DWIN32 /O2 /TP /MD \
         /D_CRT_SECURE_NO_DEPRECATE=1 /D_CRT_NON_CONFORMING_SWPRINTFS=1 \
         /D_SCL_SECURE_NO_WARNINGS=1  /D__NO_VC_CRTDBG__ /D__WXMSW__ \
         /DNDEBUG /D_UNICODE \
         /I../sg /I../util

OBJS = vfruStl.obj vfruWfObj.obj
TARGET = vfru.lib

CXX = cl -nologo -c
AR = lib /NOLOGO
LINK = link
INSTALL = copy

.SUFFIXES: .cpp .obj

.cpp.obj:
	$(CXX) $(CFLAGS) $<


$(TARGET) : $(OBJS)
	$(AR) -out:$@ $** 

install : $(TARGET)
	if not exist "..\dist\lib" mkdir "..\dist\lib"
	$(INSTALL) $(TARGET) ..\dist\lib\

clean : 
	-@erase *.obj

distclean : clean
	-@erase $(TARGET) vc*.*
