#
# MAKEFILE for vfr scene graph library
#

CFLAGS = /I../util /W3 /wo4244 /EHsc /D_WINDOWS /DWINDOWS /DWIN32 /O2 /TP /MD \
	 /D_CRT_SECURE_NO_DEPRECATE=1 /D_CRT_NON_CONFORMING_SWPRINTFS=1 \
	 /D_SCL_SECURE_NO_WARNINGS=1  /D__NO_VC_CRTDBG__ /D__WXMSW__ \
	 /DNDEBUG /D_UNICODE

LDLIBS = glu32.lib opengl32.lib

OBJS =  \
	vfrAction.obj \
	vfrArrow.obj \
	vfrBall.obj \
	vfrBase.obj \
	vfrCamera.obj \
	vfrCamera2D.obj \
	vfrCamera3D.obj \
	vfrCone.obj \
	vfrCube.obj \
	vfrCylinder.obj \
	vfrDatamap.obj \
	vfrDefaultActions.obj \
	vfrDispatch.obj \
	vfrDrawArea.obj \
	vfrEvents.obj \
	vfrFrustum.obj \
	vfrGroup.obj \
	vfrHelveticaText.obj \
	vfrImage.obj \
	vfrIndexLines.obj \
	vfrIndexPolygons.obj \
	vfrLetters.obj \
	vfrLight.obj \
	vfrLineStrip.obj \
	vfrLineText.obj \
	vfrLines.obj \
	vfrMaterial.obj \
	vfrMesh2D.obj \
	vfrNode.obj \
	vfrPrimSet.obj \
	vfrScene.obj \
	vfrScreen.obj \
	vfrTexture.obj \
	vfrTimesRomanText.obj \
	vfrTriangles.obj \
	vfrVectors.obj \

TARGET = vfr.lib

CXX = cl -nologo -c
AR = lib /NOLOGO
INSTALL = copy

.SUFFIXES: .cpp .obj

.cpp.obj:
	$(CXX) $(CFLAGS) $<


$(TARGET) : $(OBJS)
	$(AR) -out:$@ $** 

install : $(TARGET)
	if not exist "..\dist\lib" mkdir "..\dist\lib"
	$(INSTALL) $(TARGET) ..\dist\lib\

clean : 
	-@erase *.obj vc*.pdb

distclean : clean
	-@erase $(TARGET)
