// virtual keycode

#ifndef _VFR_KEY_CODE_H_
#define _VFR_KEY_CODE_H_

#define VFRKC_BACKSPACE    0x08
#define VFRKC_TAB          0x09
#define VFRKC_CLEAR        0x0c
#define VFRKC_RETURN       0x0d
#define VFRKC_PAUSE        0x13
#define VFRKC_ESCAPE       0x1b
#define VFRKC_SPACE        0x20
#define VFRKC_EXCLAIM      0x21
#define VFRKC_QUOTEDBL     0x22
#define VFRKC_HASH         0x23
#define VFRKC_DOLLAR       0x24
#define VFRKC_PERCENT      0x25
#define VFRKC_AMPERSAND    0x26
#define VFRKC_QUOTE        0x27
#define VFRKC_LEFTPAREN    0x28
#define VFRKC_RIGHTPAREN   0x29
#define VFRKC_ASTERISK     0x2a
#define VFRKC_PLUS         0x2b
#define VFRKC_COMMA        0x2c
#define VFRKC_MINUS        0x2d
#define VFRKC_PERIOD       0x2e
#define VFRKC_SLASH        0x2f
#define VFRKC_0            0x30
#define VFRKC_1            0x31
#define VFRKC_2            0x32
#define VFRKC_3            0x33
#define VFRKC_4            0x34
#define VFRKC_5            0x35
#define VFRKC_6            0x36
#define VFRKC_7            0x37
#define VFRKC_8            0x38
#define VFRKC_9            0x39
#define VFRKC_COLON        0x3a
#define VFRKC_SEMICOLON    0x3b
#define VFRKC_LESS         0x3c
#define VFRKC_EQUALS       0x3d
#define VFRKC_GREATER      0x3e
#define VFRKC_QUESTION     0x3f
#define VFRKC_AT           0x40
#define VFRKC_A            0x41
#define VFRKC_B            0x42
#define VFRKC_C            0x43
#define VFRKC_D            0x44
#define VFRKC_E            0x45
#define VFRKC_F            0x46
#define VFRKC_G            0x47
#define VFRKC_H            0x48
#define VFRKC_I            0x49
#define VFRKC_J            0x4a
#define VFRKC_K            0x4b
#define VFRKC_L            0x4c
#define VFRKC_M            0x4d
#define VFRKC_N            0x4e
#define VFRKC_O            0x4f
#define VFRKC_P            0x50
#define VFRKC_Q            0x51
#define VFRKC_R            0x52
#define VFRKC_S            0x53
#define VFRKC_T            0x54
#define VFRKC_U            0x55
#define VFRKC_V            0x56
#define VFRKC_W            0x57
#define VFRKC_X            0x58
#define VFRKC_Y            0x59
#define VFRKC_Z            0x5a
#define VFRKC_LEFTBRACKET  0x5b
#define VFRKC_BACKSLASH    0x5c
#define VFRKC_RIGHTBRACKET 0x5d
#define VFRKC_CARET        0x5e
#define VFRKC_UNDERSCORE   0x5f
#define VFRKC_BACKQUOTE    0x60
#define VFRKC_a            0x61
#define VFRKC_b            0x62
#define VFRKC_c            0x63
#define VFRKC_d            0x64
#define VFRKC_e            0x65
#define VFRKC_f            0x66
#define VFRKC_g            0x67
#define VFRKC_h            0x68
#define VFRKC_i            0x69
#define VFRKC_j            0x6a
#define VFRKC_k            0x6b
#define VFRKC_l            0x6c
#define VFRKC_m            0x6d
#define VFRKC_n            0x6e
#define VFRKC_o            0x6f
#define VFRKC_p            0x70
#define VFRKC_q            0x71
#define VFRKC_r            0x72
#define VFRKC_s            0x73
#define VFRKC_t            0x74
#define VFRKC_u            0x75
#define VFRKC_v            0x76
#define VFRKC_w            0x77
#define VFRKC_x            0x78
#define VFRKC_y            0x79
#define VFRKC_z            0x7a
#define VFRKC_DELETE       0x7f
#define VFRKC_UP           0x111
#define VFRKC_DOWN         0x112
#define VFRKC_RIGHT        0x113
#define VFRKC_LEFT         0x114
#define VFRKC_INSERT       0x115
#define VFRKC_HOME         0x116
#define VFRKC_END          0x117
#define VFRKC_PAGEUP       0x118
#define VFRKC_PAGEDOWN     0x119
#define VFRKC_F1           0x11a
#define VFRKC_F2           0x11b
#define VFRKC_F3           0x11c
#define VFRKC_F4           0x11d
#define VFRKC_F5           0x11e
#define VFRKC_F6           0x11f
#define VFRKC_F7           0x120
#define VFRKC_F8           0x121
#define VFRKC_F9           0x122
#define VFRKC_F10          0x123
#define VFRKC_F11          0x124
#define VFRKC_F12          0x125
#define VFRKC_PRINT        0x13c

#endif // _VFR_KEY_CODE_H_

